// Reads .env and writes env.generated.js, which the page loads before contact.js.
// Run via `npm run build:env` (also runs automatically on `npm start`).
const fs = require('fs');
const path = require('path');

const KEYS = [
  'EMAILJS_PUBLIC_KEY',
  'EMAILJS_SERVICE_ID',
  'EMAILJS_TEMPLATE_ID',
  'CONTACT_FALLBACK_EMAIL',
];

function parseEnv(text) {
  const out = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

// Real environment variables win over .env, so hosts that inject config
// (Vercel, Netlify, CI) work without a checked-in .env — which is gitignored
// and therefore never present on the build machine.
const envPath = path.join(__dirname, '.env');
const fileEnv = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, 'utf8')) : null;

const config = {};
for (const key of KEYS) config[key] = process.env[key] || (fileEnv && fileEnv[key]) || '';

const source = fileEnv ? '.env / environment' : 'environment';
const missing = KEYS.slice(0, 3).filter((k) => !config[k]);
if (missing.length) {
  console.warn(
    'Warning: not set in ' + source + ' -> ' + missing.join(', ') +
    '. The contact form will stay disabled until these are set.'
  );
  if (!fileEnv) {
    console.warn('No .env found either — copy .env.example to .env for local development.');
  }
}

const banner = '// GENERATED by build-env.js. Do not edit; do not commit.\n';
fs.writeFileSync(
  path.join(__dirname, 'env.generated.js'),
  banner + 'window.__ENV = ' + JSON.stringify(config, null, 2) + ';\n'
);
console.log('Wrote env.generated.js');
